version: '3.9'

services:
  psql:
    build:
      context: ./docker/psql
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./DDL:/docker-entrypoint-initdb.d
      - ./docker/psql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=go_pg
      - TZ=Asia/Tokyo
volumes:
  psql_data:
    driver: local