version: '3.9'

services:
  star:
    build:
      context: .
    container_name: star
    tty: true
    ports:
      - ${STAR_SERVER_PORT}:${STAR_SERVER_PORT}
    volumes:
      - ./:/go/src/
      - ./go.mod:/go/src/go.mod
      - ./go.sum:/go/src/go.sum
    env_file:
      - .env.local
    networks:
      - star-network
  psql:
    build:
      context: ./docker/psql
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - ${STAR_POSTGRES_PORT}:${STAR_POSTGRES_PORT}
    volumes:
      - ./DDL:/docker-entrypoint-initdb.d
      - ./docker/psql/data:/var/lib/postgresql/data
    environment:
      - STAR_POSTGRES_HOST=${STAR_POSTGRES_HOST}
      - STAR_POSTGRES_PORT=${STAR_POSTGRES_PORT}
      - STAR_POSTGRES_DB=${STAR_POSTGRES_DATABASE}
      - STAR_POSTGRES_USER=${STAR_POSTGRES_USER}
      - STAR_POSTGRES_PASSWORD=${STAR_POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - star-network
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - ${STAR_REDIS_PORT}:${STAR_REDIS_PORT}
    tty: true
    volumes:
      - ./docker/redis/data:/data
    environment:
      - STAR_REDIS_HOST=${STAR_REDIS_HOST}
    networks:
      - star-network
  localstack:
    build:
      context: ./docker/localstack
      dockerfile: Dockerfile
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - "./docker/localstack/data:/tmp/localstack/data"
    networks:
      - star-network
volumes:
  psql_data:
    driver: local
networks:
  star-network:
    external: false
