version: '3.9'

services:
  star:
    build:
      context: .
    container_name: star
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/
      - ./go.mod:/go/src/go.mod
      - ./go.sum:/go/src/go.sum
    environment:
      - STAR_POSTGRES_HOST=${STAR_POSTGRES_HOST}
      - STAR_POSTGRES_PORT=${STAR_POSTGRES_PORT}
      - STAR_POSTGRES_DB=${STAR_POSTGRES_DATABASE}
      - STAR_POSTGRES_USER=${STAR_POSTGRES_USER}
      - STAR_POSTGRES_PASSWORD=${STAR_POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
    networks:
      - star-network
  psql:
    build:
      context: ./docker/psql
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./DDL:/docker-entrypoint-initdb.d
      - ./docker/psql/data:/var/lib/postgresql/data
    environment:
      - STAR_POSTGRES_HOST=${STAR_POSTGRES_HOST}
      - STAR_POSTGRES_PORT=${STAR_POSTGRES_PORT}
      - STAR_POSTGRES_DB=${STAR_POSTGRES_DATABASE}
      - STAR_POSTGRES_USER=${STAR_POSTGRES_USER}
      - STAR_POSTGRES_PASSWORD=${STAR_POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
    networks:
      - star-network
volumes:
  psql_data:
    driver: local
networks:
  star-network:
    external: false
