package entity

type Prefecture string

const (
	PrefectureHokkaido  Prefecture = "Hokkaido"
	PrefectureAomori    Prefecture = "Aomori"
	PrefectureIwate     Prefecture = "Iwate"
	PrefectureMiyagi    Prefecture = "Miyagi"
	PrefectureAkita     Prefecture = "Akita"
	PrefectureYamagata  Prefecture = "Yamagata"
	PrefectureFukushima Prefecture = "Fukushima"
	PrefectureIbaraki   Prefecture = "Ibaraki"
	PrefectureTochigi   Prefecture = "Tochigi"
	PrefectureGunma     Prefecture = "Gunma"
	PrefectureSaitama   Prefecture = "Saitama"
	PrefectureChiba     Prefecture = "Chiba"
	PrefectureTokyo     Prefecture = "Tokyo"
	PrefectureKanagawa  Prefecture = "Kanagawa"
	PrefectureNiigata   Prefecture = "Niigata"
	PrefectureToyama    Prefecture = "Toyama"
	PrefectureIshikawa  Prefecture = "Ishikawa"
	PrefectureFukui     Prefecture = "Fukui"
	PrefectureYamanashi Prefecture = "Yamanashi"
	PrefectureNagano    Prefecture = "Nagano"
	PrefectureGifu      Prefecture = "Gifu"
	PrefectureShizuoka  Prefecture = "Shizuoka"
	PrefectureAichi     Prefecture = "Aichi"
	PrefectureMie       Prefecture = "Mie"
	PrefectureShiga     Prefecture = "Shiga"
	PrefectureKyoto     Prefecture = "Kyoto"
	PrefectureOsaka     Prefecture = "Osaka"
	PrefectureHyogo     Prefecture = "Hyogo"
	PrefectureNara      Prefecture = "Nara"
	PrefectureWakayama  Prefecture = "Wakayama"
	PrefectureTottori   Prefecture = "Tottori"
	PrefectureShimane   Prefecture = "Shimane"
	PrefectureOkayama   Prefecture = "Okayama"
	PrefectureHiroshima Prefecture = "Hiroshima"
	PrefectureYamaguchi Prefecture = "Yamaguchi"
	PrefectureTokushima Prefecture = "Tokushima"
	PrefectureKagawa    Prefecture = "Kagawa"
	PrefectureEhime     Prefecture = "Ehime"
	PrefectureKochi     Prefecture = "Kochi"
	PrefectureFukuoka   Prefecture = "Fukuoka"
	PrefectureSaga      Prefecture = "Saga"
	PrefectureNagasaki  Prefecture = "Nagasaki"
	PrefectureKumamoto  Prefecture = "Kumamoto"
	PrefectureOita      Prefecture = "Oita"
	PrefectureMiyazaki  Prefecture = "Miyazaki"
	PrefectureKagoshima Prefecture = "Kagoshima"
	PrefectureOkinawa   Prefecture = "Okinawa"
	PrefectureOversea   Prefecture = "Oversea"
)
