package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"

	grpcUser "github.com/AI1411/go-grpc-praphql/graph/grpc"
	"github.com/AI1411/go-grpc-praphql/graph/model"
	"github.com/AI1411/go-grpc-praphql/grpc"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	userClient, err := grpcUser.ConnectUserServiceClient()
	if err != nil {
		return nil, err
	}

	userClient.CreateUser(ctx, &grpc.CreateUserRequest{
		Username:     input.Username,
		Email:        input.Email,
		Password:     input.Password,
		Prefecture:   grpc.Prefecture(input.Prefecture),
		Introduction: input.Introduction,
		BloodType:    grpc.BloodType(input.BloodType),
	})

	return nil, nil
}

// GetUser is the resolver for the user field.
func (r *queryResolver) GetUser(ctx context.Context, input string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
