// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Prefecture   int    `json:"prefecture"`
	Introduction string `json:"introduction"`
	BloodType    int    `json:"bloodType"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
