// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chat struct {
	ID         string `json:"id"`
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Body       string `json:"body"`
	IsRead     bool   `json:"is_read"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type CreateChatInput struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Body       string `json:"body"`
}

type CreateRoomInput struct {
	UserID string `json:"user_id"`
}

type CreateTweetInput struct {
	UserID string `json:"user_id"`
	Body   string `json:"body"`
}

type CreateUserInput struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Prefecture   int    `json:"prefecture"`
	Introduction string `json:"introduction"`
	BloodType    int    `json:"bloodType"`
}

type DeleteRoomInput struct {
	ID string `json:"id"`
}

type GetRoomInput struct {
	ID string `json:"id"`
}

type ListChatInput struct {
	FromUserID string `json:"from_user_id"`
}

type ListRoomInput struct {
	UserID string `json:"user_id"`
}

type Room struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Tweet struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UpdateUserPasswordInput struct {
	ID                   string `json:"id"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

type UpdateUserProfileInput struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Prefecture   int    `json:"prefecture"`
	Introduction string `json:"introduction"`
	BloodType    int    `json:"bloodType"`
}

type UpdateUserStatusInput struct {
	ID     string `json:"id"`
	Status int    `json:"status"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Status       string `json:"status"`
	Prefecture   string `json:"prefecture"`
	Introduction string `json:"introduction"`
	BloodType    string `json:"bloodType"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}
