package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"

	"github.com/AI1411/go-grpc-praphql/graph/model"
)

// ListTweet is the resolver for the listTweet field.
func (r *queryResolver) ListTweet(ctx context.Context, input string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: ListTweet - listTweet"))
}
